log-level: INFO
default-groups:
  - '=players'
permission-order: # order of application; reverse order of precedence; last overrides first
  - server
  - world
implicit-permission:
  user: 'server.user.{0}'
  group: 'server.group.{0}'
version: @VERSION@