logLevel: INFO
setPlayerName: true
messages:
    requiresArgument: '-> Required §cargument missing§r: {1}' # 1 = Argument
    principalNotFound: '-> Principal §cnot found§r: {1}' # 1 = <Principal>
    playerNotFound: '-> Player §cnot found§r: {1}' # 1 = <Player>
    notSet: '-> {1} does §enot directly set§r {2} in {3}' # 1 = Principal, 2 = Permission, 3 = World
    unset: '-> {1} §eno longer directly sets§r {2} in {3}' # 1 = Principal, 2 = Permission, 3 = World
    alreadySet: '-> {1} §ealready directly sets§r {2} {3} in {4}' # 1 = Principal, 2 = Permission, 3 = Value, 4 = World
    set: '-> {1} §2now directly sets§r {2} {3} in {4}' # 1 = Principal, 2 = Permission, 3 = Value, 4 = World
    reload: '-> {1} plugin §2reloaded' # 1 = Plugin Name
    check:
        format: '-> {1}@{2} {3} {4} {5}{6}' # 1 = Player, 2 = World, 3 = Nature, 4 = Permission, 5 = Value, 6 = Temporary
        +set: '§9effectively sets§r'
        +default: '§deffectively defaults§r'
        +notConfigured: '§8does not configure§r'
        +direct: '§9directly configures§r'
        +inherit: '§dimplicitly configures§r'
        +true: '§atrue§r'
        +false: '§cfalse§r'
        +temporary: '§7temporarily§r'
version: @VERSION@