# @version @VERSION@
#
# ---- comments ----
# permission-order: order of application; reverse order of precedence; last overrides first
#
# ---- values ----
log-level: INFO
default-groups:
  - '=players'
permission-order:
  - server
  - world
implicit-permission:
  user: 'server.user.{0}'
  group: 'server.group.{0}'
create-maximum: 5