name: AccessControl
version: @VERSION@
description: Native Bukkit permission management
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/AccessControl
main: edgruberman.bukkit.accesscontrol.Main
commands:
    'accesscontrol:check':
        aliases: [p, 'p?', permissions, permission, perm, check]
        description: Get current effective or total (with world) value of a specific permission
        permission: accesscontrol.check
        usage: /<command> <Permission>[ (<Player>|<Principal> <World>)]
    'accesscontrol:grant':
        aliases: ['p+', grant]
        description: Set direct permission entry as true
        permission: accesscontrol.grant
        usage: /<command> <Permission> [ <Principal>[ <World>]][ (+user|+group)]
    'accesscontrol:revoke':
        aliases: ['p-', revoke]
        description: Set direct permission entry as false
        permission: accesscontrol.revoke
        usage: /<command> <Permission> [ <Principal>[ <World>]][ (+user|+group)]
    'accesscontrol:unset':
        aliases: ['p_', unset]
        description: Remove direct permission entry
        permission: accesscontrol.unset
        usage: /<command> <Permission>[ <Principal>[ <World>]]
    'accesscontrol:reload':
        description: Reload AccessControl plugin
        permission: accesscontrol.reload
permissions:
    accesscontrol.admin:
        description: Can use all features
        default: op
        children:
            accesscontrol.check: true
            accesscontrol.grant: true
            accesscontrol.revoke: true
            accesscontrol.unset: true
            accesscontrol.reload: true
    accesscontrol.check:
        description: Can use check command
        default: false
    accesscontrol.grant:
        description: Can use grant command
        default: false
    accesscontrol.revoke:
        description: Can use revoke command
        default: false
    accesscontrol.unset:
        description: Can use unset command
        default: false
    accesscontrol.reload:
        description: Can use reload command
        default: false