name: AccessControl
version: @VERSION@
description: Permission and group management
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/AccessControl
main: edgruberman.bukkit.accesscontrol.Main
commands:
  'accesscontrol:check':
    aliases: [check]
    description: Shows current value of permission for player
    permission: accesscontrol.check
    usage: '§f-> §7Usage: §b/<command> §3§opermission §3[§oplayer§3]'
  'accesscontrol:effective':
    aliases: [effective]
    description: List all permissions and current values for player
    permission: accesscontrol.effective
    usage: '§f-> §7Usage: §b/<command> §3[§opage§3] [§oplayer§3] [§omatch§3]'
  'accesscontrol:trace':
    aliases: [trace]
    description: Configured assignments of permission for principal
    permission: accesscontrol.trace
    usage: '§f-> §7Usage: §b/<command> §3§opermission §3[§oname§3] [§otype§3] [§ocontext§3]'
  'accesscontrol:default':
    aliases: [default]
    description: Shows default value of permission for player
    permission: accesscontrol.default
    usage: '§f-> §7Usage: §b/<command> §3§opermission §3[§oplayer§3]'
  'accesscontrol:deny':
    aliases: [deny]
    description: Set direct permission entry as false
    permission: accesscontrol.deny
    usage: '§f-> §7Usage: §b/<command> §3§opermission §3[§oname§3] [§otype§3] [§ocontext§3]'
  'accesscontrol:grant':
    aliases: [grant]
    description: Set direct permission entry as true
    permission: accesscontrol.grant
    usage: '§f-> §7Usage: §b/<command> §3§opermission §3[§oname§3] [§otype§3] [§ocontext§3]'
  'accesscontrol:revoke':
    aliases: [revoke]
    description: Remove direct permission entry
    permission: accesscontrol.revoke
    usage: '§f-> §7Usage: §b/<command> §3§opermission §3[§oname§3] [§otype§3] [§ocontext§3]'
  'accesscontrol:reload':
    description: Reload AccessControl plugin
    permission: accesscontrol.reload
    usage: '§f-> §7Usage: §b/<command>'
permissions:
  accesscontrol.user:
    description: Can use basic features
    default: true
  accesscontrol.admin:
    description: Can use all features
    default: op
    children:
      accesscontrol.check: true
      accesscontrol.effective: true
      accesscontrol.trace: true
      accesscontrol.default: true
      accesscontrol.deny: true
      accesscontrol.grant: true
      accesscontrol.revoke: true
      accesscontrol.reload: true
  accesscontrol.check:
    description: Can use check command
    default: false
  accesscontrol.effective:
    description: Can use effective command
    default: false
  accesscontrol.trace:
    description: Can use trace command
    default: false
  accesscontrol.default:
    description: Can use default command
    default: false
  accesscontrol.deny:
    description: Can use deny command
    default: false
  accesscontrol.grant:
    description: Can use grant command
    default: false
  accesscontrol.revoke:
    description: Can use revoke command
    default: false
  accesscontrol.reload:
    description: Can use reload command
    default: false