name: AccessControl
version: @VERSION@
description: Native Bukkit permission management
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/AccessControl
main: edgruberman.bukkit.accesscontrol.Main
commands:
    'accesscontrol:check':
        aliases: ['p?', p, check]
        description: Get current effective or total (with world) value of a specific permission
        permission: accesscontrol.check
        usage: /<command> <Permission>[ (<Player>|<Principal> <World>)]
    'accesscontrol:set':
        aliases: [p+, set]
        description: Add direct permission entry
        permission: accesscontrol.set
        usage: /<command> <Permission> [(true|false)[ <Principal>[ <World>]]][ (+user|+group)]
    'accesscontrol:unset':
        aliases: [p-, unset]
        description: Remove direct permission entry
        permission: accesscontrol.unset
        usage: /<command> <Permission>[ <Principal>[ <World>]]
    'accesscontrol:reload':
        description: Reload AccessControl plugin
        permission: accesscontrol.reload
permissions:
    accesscontrol.all:
        description: Can use all AccessControl plugin commands
        default: op
        children:
            accesscontrol.check: true
            accesscontrol.set: true
            accesscontrol.unset: true
            accesscontrol.reload: true
    accesscontrol.check:
        description: Can use check command
        default: false
    accesscontrol.set:
        description: Can use set command
        default: false
    accesscontrol.unset:
        description: Can use unset command
        default: false
    accesscontrol.reload:
        description: Can use reload command
        default: false